
schema_version = "2.1.0"

id = "rhino_to_blender"

version = "2.1.0"

name = "Rhino to Blender"

tagline = "Rhino to Blender，Blender to Rhino"

maintainer = "CP-Design"

type = "add-on"

permissions = ["file"]

website = "https://github.com/chenpaner"

tags = ["Add Mesh"]

blender_version_min = "4.0.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

copyright = ["2024 Campbell Barton"]

